#Requires AutoHotkey v2.0

outputFile := "Output\WordCombinations.ahk"
StartTime := A_TickCount

FileAppend("; Word combinations generated by WordGroupsSorter.ahk`n"
         . "; Compiled into one file by File2Var.ahk`n`n", outputFile)
loop files "WordGroups\*.txt"
{
    words := StrReplace(RTrim(FileRead(A_LoopFileFullPath), "`n`r"), "`n", ",")
    var := RTrim(A_LoopFileName, ".txt")
    result := "wordcomb_" . var . ":=" "`"" . words . "`"" . "`n"
    FileAppend(result, outputFile)
}

DirDelete("WordGroups", 1)
ElapsedTime := A_TickCount - StartTime

MsgBox "Compilation completed in " (ElapsedTime/1000) " seconds."