#Requires AutoHotkey v2.0

StartTime := A_TickCount
wordLimit := 50 ; Change if necessary
outputFile := "Output\WordCounts.ahk"
dictionary := FileRead("dictionary.txt")
FileAppend("; Generated by Dict2VarCounts.ahk`n`n", outputFile)

Loop wordLimit
{
    workingLength := wordLimit + 1 - A_Index
    hasWord := 0
    Loop Parse, dictionary, "`n", "`r"
    {
        if (StrLen(A_LoopField) = workingLength)
        {
            if (!hasWord) {
                FileAppend("lettercount_" workingLength . " := `"`n(`n" . A_LoopField, outputFile)
                hasWord := 1
            } else {
                FileAppend("`n" A_LoopField, outputFile)
            }
        }
    }

    if (hasWord) {
        FileAppend("`n)`"`n", outputFile)
    }
}

ElapsedTime := A_TickCount - StartTime
MsgBox "Finished operation in " (ElapsedTime/1000) " seconds."